name: Test
on:
    push:
        branches:
        - main
        tags: 
        - 'v*.*.*'
    pull_request:
        branches:
        - main
    workflow_dispatch:
    schedule:
        - cron: "0 */2 * * *"

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version: stable
            - name: Download Dependencies
              run: go mod download
            - name: Run Tests
              run: go tool gotestsum --format testname --junitfile=junit.xml -- -v ./... -timeout 5s
            - name: Upload Test Results to Trunk.io
              if: ${{ !cancelled() }}
              uses: trunk-io/analytics-uploader@main
              with:
                junit-paths: "**/junit.xml"        
                org-slug: adam-test
                token: ${{ secrets.TRUNK_API_TOKEN }}
